@startuml i9chat_api_arch
!include <C4/C4_Component>

title Component Diagram for i9chat API Server

' Container(api, "i9chat API Server", "Go")

System_Ext(emailSystem, "Email System", "Google SMTP")
System(cloudStorageSystem, "Cloud Storage System", "Google Cloud Storage")

ContainerDb(database, "Database", "PostgreSQL")
ContainerDb(kvstore, "Key-Value Store Database", "Redis")
ContainerQueue(eventStream, "Event-Stream Messaging System", "Redis Streams")
ContainerQueue(pubsubMS, "Pub/Sub Messaging System", "Redis Pub/Sub")

Component(cloudStorageService, "Cloud Storage Service", "GCS Go client library", "Consists functions for GCS bucket management, converting object cloud names to download URLs")
Rel(cloudStorageService, cloudStorageSystem, "Uses")

Component(cache, "Cache", "Redis, go-redis", "Consists functions that manage data in Redis")
Rel(cache, kvstore, "Reads/Writes")

Component(securityServices, "Security Services", "Go, golang-jwt, bcrypt", "Consists security functions for JWT signing/verification, generating 6-digit token/code with expiration etc.")
Component(mailService, "Mail Service", "Go, gomail.v2, crypto/tls", "Consists a function for sending email to client")
Component(eventStreamService, "Event Stream Service", "Go, go-redis (XAdd)", "Consists functions for queueing events into Redis Streams")
Rel(mailService, emailSystem, "Uses")
Rel(eventStreamService, eventStream, "Queue events in")

Component(realtimeService, "Realtime Service", "Go, sync.Map, go-redis (Publish, Subscribe), websocket", "Consists functions for managing active user sockets, subscribing clients to pub/sub channels for realtime updates, publishing messages to channels, sending server event messages like new-chat, new-message, new-post, new-notification etc. to client")
Rel(realtimeService, pubsubMS, "Calls (Publish/Subscribe)")

Component(userControllers, "User Controllers", "Fiber v3, MessagePack", "Consists request handlers for user profile management, finding other users, and getting user chats")
Component(userService, "User Service", "Go", "Consists functions that provide required user services to user controllers, and other controllers including signup, signin, and realtime controller (for user presence change)")
Component(userModel, "User Model", "Neo4j, Cypher, neo4j-go-driver, go-redis", "Consists functions that encapsulates user-related database WRITE logic and return resulting data to calling user services. Consists functions that build user-related UI components from READ-ing relevant cache (Redis) entries")
Rel(userControllers, userService, "Calls")
Rel(userService, userModel, "Calls")
Rel(userService, cloudStorageService, "Calls")
Rel(userModel, database, "Reads/Writes")
Rel(userModel, cache, "Calls")
Rel(userService, realtimeService, "Calls")
Rel(userService, eventStreamService, "Calls")

Component(signupControllers, "Signup Controllers", "Fiber v3, MessagePack", "Consists request handlers for the 3-step user signup process (new account request, email verification, and final user registration) and signup session management")
Component(signupService, "Signup Service", "Go", "Consists functions that provide required services to signup controllers; user existence checks, mailing verification code and setting code expiration, signup session data generation, password encryption, creating user account, auto-login user by signing a JWT token")
Rel(signupControllers, signupService, "Call")
Rel(signupService, userService, "Calls")
Rel(signupService, securityServices, "Calls")
Rel(signupService, mailService, "Calls")

Component(signinControllers, "Signin Controllers", "Fiber v3, MessagePack", "Consists request handler for user signin")
Component(signinService, "Signin Service", "Go", "Consists a function that provide the required service to the signin controller; user existence checks, password matching check, JWT token signing")
Rel(signinControllers, signinService, "Calls")
Rel(signinService, userService, "Calls")
Rel(signinService, securityServices, "Calls")

Component(passwordResetControllers, "Password Reset Controllers", "Fiber v3, MessagePack", "Consists request handlers for the 3-step user password reset process (password reset request, email confirmation, and final password change) and password reset session management")
Component(passwordResetService, "Password Reset Service", "Go", "Consists functions that provide required services to password reset controllers; email existence check, mailing confirmation token and setting token exipration, password reset session data generation, password encryption, and user account password change")
Rel(passwordResetControllers, passwordResetService, "Calls")
Rel(passwordResetService, userService, "Calls")
Rel(passwordResetService, securityServices, "Calls")
Rel(passwordResetService, mailService, "Calls")

Component(chatUploadControllers, "Chat Upload Controllers", "Fiber v3, MessagePack", "Consists request handlers for message media upload authorizaton")
Component(chatUploadService, "Chat Upload Service", "Go", "Consists functions that provide required services to chat upload controllers")
Rel(chatUploadControllers, chatUploadService, "Calls")
Rel(chatUploadService, cloudStorageService, "Calls")

Component(directChatControllers, "Direct Chat Controllers", "Fiber v3, MessagePack", "Consists HTTP request and WebSocket message handlers for direct chat and messaging operations")
Component(directChatService, "Direct Chat Service", "Go", "Consists functions that provide required services to Direct Chat controllers")
Component(directChatModel, "Direct Chat Model", "Neo4j, Cypher, neo4j-go-driver, go-redis", "Consists functions that encapsulates direct-chat-related database WRITE logic and return resulting data to calling direct chat services. Consists functions that build direct-chat-related UI components from READ-ing relevant cache (Redis) entries")
Rel(directChatControllers, directChatService, "Calls")
Rel(directChatService, directChatModel, "Calls")
Rel(directChatService, realtimeService, "Calls")
Rel(directChatService, eventStreamService, "Calls")
Rel(directChatService, cloudStorageService, "Calls")
Rel(directChatModel, cache, "Calls")
Rel(directChatModel, database, "Reads/Writes")

Component(groupChatControllers, "Group Chat Controllers", "Fiber v3, MessagePack", "Consists HTTP request and WebSocket message handlers for group chat & messaging and group management operations")
Component(groupChatService, "Group Chat Service", "Go", "Consists functions that provide required services to Group Chat controllers")
Component(groupChatModel, "Group Chat Model", "Neo4j, Cypher, neo4j-go-driver, go-redis", "Consists functions that encapsulates group-chat-related database WRITE logic and return resulting data to calling group chat services. Consists functions that build group-chat-related UI components from READ-ing relevant cache (Redis) entries")
Rel(groupChatControllers, groupChatService, "Calls")
Rel(groupChatService, groupChatModel, "Calls")
Rel(groupChatService, eventStreamService, "Calls")
Rel(groupChatService, realtimeService, "Calls")
Rel(groupChatService, cloudStorageService, "Calls")
Rel(groupChatModel, cache, "Calls")
Rel(groupChatModel, database, "Reads/Writes")

Component(realtimeController, "Realtime Controller", "Fiber v3, MessagePack, WebSocket", "Handles Websocket HTTP Upgrade. Manages client connection stream (socket). Reads request messages from the client connection stream (socket), calls target WS message handlers in direct and group chat controllers, and writes reply back to the client socket. It also calls other services for required services")
Rel(realtimeController, directChatControllers, "Calls")
Rel(realtimeController, groupChatControllers, "Calls")
Rel(realtimeController, userService, "Calls")
Rel(realtimeController, realtimeService, "Calls")

Component(backgroundWorkers, "Background Workers", "Go, go-redis", "Consist long-running functions that consume stream messages (dequeueing events) and execute background tasks including caching, realtime, eventual message delivery, and other expensive, side data-manipulation operations")
BiRel(backgroundWorkers, eventStream, "Dequeue events from")
Rel(backgroundWorkers, database, "Read/Write")
Rel(backgroundWorkers, cache, "Calls")
Rel(backgroundWorkers, realtimeService, "Calls")

@enduml


